@startuml
skinparam componentStyle uml2

node "VPC-1 (10.0.0.0/16)" as VPC1
node "VPC-2 (10.1.0.0/16)" as VPC2
node "Route 53 PHZ (example.internal)" as PHZ

VPC1 -down-> PHZ: <<Association>>
VPC2 -down-> PHZ: <<Association>>

node "EC2 in VPC-2" as EC2
EC2 -up-> PHZ: DNS Query (db.example.internal)
PHZ -up-> EC2: DNS Record (IP)
@enduml
