@startuml
skinparam componentStyle uml2
node "On-Premises" {
    [Customer Gateway] as CGW
}
cloud "Internet" {
    [ISP]
}
node "AWS" {
    [Transit Gateway] as TGW
}
CGW -right-> ISP: Tunnel 1 (UDP 4500)
CGW -right-> ISP: Tunnel 2 (UDP 4500)
ISP -right-> TGW
@enduml
